on:
  push:
    branches:
      - master
name: Build and deploy on pushes to master
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
